name: Waka Readme

on: 
  schedule:
    #Runs every 4 hours
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest 

    steps:
      - uses: anmol098/waka-readme-stats@master
        with: 
          WAKATIME_API_KEY: 11w1Hv7iRWd0+4G79DfE5qlEXOawW4nEoNGOtcGh2Qo=
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_SHORT_INFO: "False"
